### ISSUE TITLE
Mattermost wrong redirect_uri for GitLab SSO when using custom HTTPS port

### ISSUE THREAD

**Issue by craph** [mattermost/mattermost-server#13059]
#### Summary
Sigin-in/Authenticating via SSO with GitLab won't work because the generated URI doesn't contains the right port number if Mattermost runs on another port like 443.

#### Steps to reproduce

1. Run Mattermost docker on port 4434 instead of 443

1. Add an application in GitLab -> admin area -> applications

1. enable SSO with GitLab, by setting up in config.json

1. try to login with the GitLab button

Here is my docker-compose.yml file for Mattermost :
```yaml
version: "3"

services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      args:
        - edition=team
      #   - PUID=1000
      #   - PGID=1000
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - MM_SERVICESETTINGS_SITEURL=https://mymattermost

      # use the credentials you've set above, in the format:
      # MM_SQLSETTINGS_DATASOURCE=postgres://${MM_USERNAME}:${MM_PASSWORD}@db:5432/${MM_DBNAME}?sslmode=disable&connect_timeout=10
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10

      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  web:
    build: web
    ports:
      - "8008:80"
      - "4434:443"
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    environment:
      - MATTERMOST_ENABLE_SSL=true

```

And here is my config.json about GitLab settings for SSO:
```yaml
"GitLabSettings": {
        "Enable": true,
        "Secret": "secret",
        "Id": "id",
        "Scope": "",
        "AuthEndpoint": "https://mygitlab/oauth/authorize",
        "TokenEndpoint": "https://mygitlab/oauth/token",
        "UserApiEndpoint": "https://mygitlab/api/v4/user"
    },

```

And in GitLab -> Admin aera -> applications :

```
Callback URL
https://mymattermost:4434/signup/gitlab/complete
https://mymattermost:4434/login/gitlab/complete
```

#### Expected behavior
After clicking the SSO button on Mattermost, it will redirect me to GitLab where I have to login-in and authorize the Application to use my account data. After authorizing GitLab should redirect me to Mattermost where I'm logged in now.

#### Observed behavior (that appears unintentional) 
When I click on the GitLab button in the Developper tools from Chrome I can see that the generated redirect_uri doesn't contains the port 4434

Request URL: https://mymattermost:4434/oauth/gitlab/login
Request Method: GET
Status Code: 302 
Remote Address: 10.81.69.82:4434
Referrer Policy: no-referrer
content-length: 0
content-type: application/json
date: Tue, 12 Nov 2019 12:20:16 GMT
expires: 0
location: https://mygitlab/oauth/authorize?response_type=code&client_id=<client_id>&redirect_uri=https%3A%2F%2Fmymattermost%2Fsignup%2Fgitlab%2Fcomplete&state=eyJhY3Rpb24iOiJsb2dpbiIsInRva2VuIjoiZDNpeWVlb2NxNmFibWR4NGhkNW4zczRmeThrZG05a2g1dWRrYmZyb283M3FoYzkzMWduajZuaGJkaWt0a2loOCJ9

Here the port is missing...

#### Possible fixes
May be it's linked to this issue : #3944

**Comment by amyblais** [comment]
@hmhealey Are you familiar with this issue?

**Comment by craph** [comment]
Hi @amyblais ,

I found my issue. It was a mistake from me. I forgot to specify the port in the environment variable : **MM_SERVICESETTINGS_SITEURL**

After adding the port, the redirect_uri seems correct but now, I have the following error : 

```
Error
Token request failed

Back to Mattermost
```

And in the Mattermost log :
`{"level":"error","ts":1573570165.5886054,"caller":"web/oauth.go:259","msg":"AuthorizeOAuthUser: Token request failed, Post https://mygitlab/oauth/token: x509: certificate signed by unknown authority"}`

But I don't know where I can specify my custom CA because mygitlab and mymattermost are selfsigned certificate from my company.

Should I add it in nginx or mattermost container ? I can't find any specification in the documentation for that

**Comment by hmhealey** [comment]
I'm not familiar with setting up self-signed certificates, but as far as I know, MM looks in the standard locations provided by the OS. That error is definitely from Mattermost, so I don't know if GitLab also has some special steps to trust self-signed certificates as well

**Comment by craph** [comment]
Yes GitLab have special steps to trust self-signed certificates.

My GitLab server is working fine from 2 years with self signed certificate.

Here is a search about that : 
https://gitlab.com/search?utf8=%E2%9C%93&search=trusted-certs&group_id=&project_id=20699&search_code=true&repository_ref=&nav_source=navbar

**Comment by craph** [comment]
I have try to add my trusted CA in `/usr/local/share/ca-certificates` in the Mattermost docker container but I'm unable to launch the command :` update-ca-certificates`

I have : Failed to open temporary file /etc/ssl/certs/bundleXXXXXX for ca bundle

**Comment by craph** [comment]
As discussed with the GitLab support here is a status about this issue :

> [This question](https://forum.mattermost.org/t/docker-swarm-token-request-failed-certificate-signed-by-unknown-authority/6966/3) looks similar, and points out that you should mount the certificate under `/etc/ssl/certs/` in Mattermost.
> 
> Also, the error appears to be OS dependent, [some users reported seeing this in some alpine versions](https://github.com/gliderlabs/docker-alpine/issues/148) but not others. In the official Mattermost DockerFile you use alpine 3.10 for the app, according to the reports alpine 3.2 didn't show this error.

So may be the error is related to Alpine and need some fix.

By the way, I fixed my error by adding my trusted CA in `/etc/ssl/certs` in the docker-compose.yml like this :
I have added this line in the volumes for the app which contains my trusted CA : 
`- /root/certpki/pki_chain.pem:/etc/ssl/certs/pki_chain.pem:ro`

```yaml
version: "3"

services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      args:
        - edition=team
      #   - PUID=1000
      #   - PGID=1000
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /root/certpki/pki_chain.pem:/etc/ssl/certs/pki_chain.pem:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - MM_SERVICESETTINGS_SITEURL=https://mymattermost:4434

      # use the credentials you've set above, in the format:
      # MM_SQLSETTINGS_DATASOURCE=postgres://${MM_USERNAME}:${MM_PASSWORD}@db:5432/${MM_DBNAME}?sslmode=disable&connect_timeout=10
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10

      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  web:
    build: web
    ports:
      - "8008:80"
      - "4434:443"
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    environment:
      - MATTERMOST_ENABLE_SSL=true

```

So please could have a look about trusted CA, update the official documentation and check with Alpine ?

Thank you very much for your help.
