### ISSUE TITLE
GitLab SSO: The redirect URI included is not valid

### ISSUE THREAD

**Issue by lucasscheepers** [mattermost/mattermost-server#18990]
**Summary**
The error “The redirect URI included is not valid.” when logging in to Mattermost with GitLab

**Steps to reproduce**
I'm using the latest version of Mattermost [Free version] and the official www.gitlab.com. So no self hosted gitlab or something.

**Expected behavior**
Logging in to Mattermost with GitLab

**Observed behavior**
I'm getting the error `The redirect URI included is not valid`. The uri's are:
`http://localhost:8065/login/gitlab/complete`
`http://localhost:8065/login/gitlab/complete`

Also tried it with a deployment in AWS but got the same result..

Checked the link https://docs.mattermost.com/onboard/sso-gitlab.html
I noticed the sentence at Step 1 - 2C: `Do not select any options under Scopes.`. Unfortunately this is not possible since it is required to select at least one option.

**Comment by amyblais** [comment]
Would any of these troubleshooting threads help?
 - https://forum.mattermost.org/t/solved-the-redirect-uri-included-is-not-valid-after-mmost-url-change/931
 - https://forum.mattermost.org/t/the-redirect-uri-is-not-valid-during-oauth-on-on-new-gitlab-v8-2-2-omnibus-installation/633/2
 - https://forum.mattermost.org/t/cannot-log-in-with-gitlab/5027
 - https://stackoverflow.com/questions/56476104/the-redirect-uri-included-is-not-valid

**Comment by lucasscheepers** [comment]
Hi @amyblais,
Thanks for answering. I'm struggling with this issue quite some time now..

First of all is GitLab SSO on http://localhost:8065 possible or does it has to be publicly accessible?

Some of these threads I already saw. In the first thread they're referring to `/etc/gitlab/gitlab.rb` and a mattermost_external_url. In the second thread they're also referring to a mattermost_external_url. I can't find that file anywhere. If this is a file from a self-hosted GitLab server this won't help for me, since I'm using my personal GitLab account on www.gitlab.com for now. I looked in the mattermost pods and found the some configuration in the file `/mattermost/config/config.json`:
```json
  "GitLabSettings": {
    "Enable": false,
    "Secret": "",
    "Id": "",
    "Scope": "",
    "AuthEndpoint": "",
    "TokenEndpoint": "",
    "UserAPIEndpoint": "",
    "DiscoveryEndpoint": "",
    "ButtonText": "",
    "ButtonColor": ""
  },
```
All of it is empty, but I did the configuration in the UI of Mattermost System Console. I don't know if this has to be changed. And if I change it in the shell of the two mattermost pods, will this be permanent and the correct way?

The third thread I didn't see yet. They're referring to the file `/var/opt/gitlab/mattermost/config.json`. Is this the same file I stated above?}

In the fourth thread he fixed it by changing the url from `http://localhost:5000` to `http://localhost:5000/`. I also did this for those urls: 
`http://localhost:8065/login/gitlab/complete/`
`http://localhost:8065/login/gitlab/complete/`
Those urls are indeed accessible in the browser instead of the urls without the `/` symbol. But I'm getting the same error from GitLab.


Is it maybe possible/a solution to configure this a right way in the installation file? The mattermost-installation.yml file looks like this.
```yml
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost-iv                                                         # Choose the desired name
spec:
  size: 1000users                                                             # Adjust to your requirements
  useServiceLoadBalancer: true                                                # Set to true to use AWS or Azure load balancers instead of an NGINX controller.
  ingressName: mattermost.iv                                                  # Hostname used for Ingress, e.g. example.mattermost-example.com. Required when using an Ingress controller. Ignored if useServiceLoadBalancer is true.
  ingressAnnotations:
    kubernetes.io/ingress.class: nginx
  version: 6.0.0
  licenseSecret: ""                                                           # Name of a Kubernetes secret that contains Mattermost license. Required only for enterprise installation.
  database:
    external:
      secret: db-credentials                                                  # Name of a Kubernetes secret that contains connection string to external database.
  fileStore:
    external:
      url: s3.amazonaws.com                                                   # External File Storage URL.
      bucket: **********                                               # File Storage bucket name to use.
      secret: file-store-credentials
  mattermostEnv:
  - name: MM_FILESETTINGS_AMAZONS3SSE
    value: "false"
  - name: MM_FILESETTINGS_AMAZONS3SSL
    value: "false"
---

# External database PostgreSQL (check https://docs.mattermost.com/install/install-kubernetes.html for MySQL)

apiVersion: v1
data:
  DB_CONNECTION_STRING: ********
kind: Secret
metadata:
  name: db-credentials
type: Opaque
---
# External file storage S3

apiVersion: v1
data:
  accesskey: *********
  secretkey: ********
kind: Secret
metadata:
  name: file-store-credentials
type: Opaque
```
