### ISSUE TITLE
Significant performance regression while using AWS S3 file storage

### ISSUE THREAD

**Issue by Vovcharaa** [mattermost/mattermost-server#19412]
#### Summary
Downloading, uploading of files and server startup time significantly increased after updating mattermost server to 6.1+ from 6.0.4.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Currently using 6.0.4 with no issues.
Any attemt of upgrade to 6.1+ (tried 6.1.0 and 6.3.1) leads to completly unusable state of the server.
Same behavior with fresh install and S3 file storage configured on version 6.3.1
Deployed on Ubuntu 20.04 using Docker Image https://hub.docker.com/r/mattermost/mattermost-team-edition .
Database: AWS RDS Postgres 12.7

#### Expected behavior
No performance regression while using AWS S3 file storage.

#### Observed behavior (that appears unintentional) 
Data below for version 6.3.1:
Server startup time = 8 min (Server startup while downgrading to 6.0.4 = ~10 seconds)
```
{"timestamp":"2022-01-22 21:18:20.621 Z","level":"info","msg":"Server is initializing...","caller":"app/server.go:237","go_version":"go1.16.7"}
...
{"timestamp":"2022-01-22 21:26:39.060 Z","level":"debug","msg":"Connection to S3 or minio is good. Bucket exists.","caller":"filestore/s3store.go:178"}
{"timestamp":"2022-01-22 21:26:39.063 Z","level":"info","msg":"Starting Server...","caller":"app/server.go:1163"}
{"timestamp":"2022-01-22 21:26:39.067 Z","level":"info","msg":"Server is listening on [::]:8065","caller":"app/server.go:1236","address":"[::]:8065"}
```
Downloading file = 1-2 min only for downloading to start.
Uploading file = 2-3 min with processing status.
Test Connection Button in File Storage settings = 2 min with success status.

**Comment by amyblais** [comment]
@Willyfrog Do you know which team could take a look at this?

(Doesn't have to be SET, I'm just looking for guidance on who would have best knowledge on this. Also, I'm wondering if this is related to our ongoing internal performance investigations, or if this is a different issue).

**Comment by Willyfrog** [comment]
@Vovcharaa can you share the specs of what you are using? and any special config you might have?

**Comment by Vovcharaa** [comment]
Server deployed on AWS EC2
OS: `Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1027-aws x86_64)`
Docker: 
```
sudo docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
docker-compose:
```
docker-compose version 1.27.4, build unknown
docker-py version: 4.4.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```
docker-compose.yml
(For update only image tag is changed)
```
version: '3.8'
services:
    mattermost:
        image: 'mattermost/mattermost-team-edition:6.0.4'
        restart: unless-stopped
        ports:
         - 8065:8065
        extra_hosts:
         - 'dockerhost:127.0.0.1'
        volumes:
         - ./mattermost/config:/mattermost/config:rw
         - ./mattermost/data:/mattermost/data:rw
         - ./mattermost/logs:/mattermost/logs:rw
         #- ./mattermost/plugins:/mattermost/plugins:rw
         #- ./mattermost/client-plugins:/mattermost/client/plugins:rw
         - /etc/localtime:/etc/localtime:ro
        environment:
         # set same as db credentials and dbname
         # use the credentials you've set above, in the format:
         #- MM_SQLSETTINGS_DATASOURCE=postgres://${MM_USERNAME}:${MM_PASSWORD}@db:5432/${MM_DBNAME}?sslmode=disable&connect_timeout=10
         - MM_SQLSETTINGS_DATASOURCE=postgres://LOGIN:PASSWORD@mattermost.XXX.eu-north-1.rds.amazonaws.com:5432/mattermost?connect_timeout=10
         #sslmode=disable&
```
Database: AWS RDS PostgreSQL 12.7
Config: [config.zip](https://github.com/mattermost/mattermost-server/files/7942154/config.zip)
