### ISSUE TITLE
The possibility to add securityContext in the manifest file while using the Helm Mattermost Operator

### ISSUE THREAD

**Issue by lucasscheepers** [mattermost/mattermost-server#20036]
The possibility to add `securityContext` in the manifest file while using the Helm Mattermost Operator, like below:

```yml
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
  namespace: $NAMESPACE
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
...
```

Related issue: https://github.com/mattermost/mattermost-helm/issues/315#issue-1167316397.
This is already possible in the team and enterprise editions Helm charts, but this is not the case for the manifest file. Or is it :sweat_smile: ?
