### ISSUE TITLE
mm on pi4(arm)?

### ISSUE THREAD

**Issue by dolphin-cat** [mattermost/mattermost-server#23387]
how do i compile a mattermost-server docker image for linux/arm64

**Comment by dolphin-cat** [comment]
i see no clear instructions there, all i see is some outdated code and some non outdated code and a "use them together" without any explanation how to do so

**Comment by amyblais** [comment]
> how do i compile a mattermost-server docker image for linux/arm64

@nab-77 Would you know the answer to this, or is this something we're planning to support?

**Comment by mmospanenko** [comment]
here you have 'buildx' step, why if you'll add something like

`
...
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'amd64,arm64/v8'
...
      - name: Build image and push 
        uses: docker/build-push-action@v3
        with:
          platforms: 'amd64,arm64'    
        .... 
`

https://github.com/mattermost/mattermost/blob/b20ef95b9124e2eb666c59f28a918952124b626f/.github/workflows/artifacts.yml#L56C18-L56C18

**Comment by this-is-tobi** [comment]
Hi @mmospanenko, 

If we take a closer look at [this line] (https://github.com/mattermost/mattermost/blob/master/.github/workflows/artifacts.yml#L65), we can notice that there is another problem, the binary used is for `amd64` and it is hardcoded. My suggestion would be as follows: 
- Hamonize the code with the `mattermost-operator` image but this is a deeper refactor in the docker build system: 
  1. Evaluate the target architecture inside the docker file with the `TARGETARCH` variable (see https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope).
  2. Download the correct binary using the above variable.
  3. In the `.github/workflows/artifacts.yml#66` pipeline, run the docker build command with the `--platform="linux/amd64,linux/arm64" flag.

OR

- Use a [matrix pipeline] (https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) with multiple architectures so that a variable inside the pipeline can be used to download the correct binary and set the correct docker target platform.

*__Note:__ I detected a similar problem on the `mattermost-operator` image and opened a [PR](https://github.com/mattermost/mattermost-operator/pull/360) for it.*

I wanted to make a PR to fix this but if we look at [this line] (https://github.com/mattermost/mattermost/blob/master/.github/workflows/artifacts.yml#L66) we can see that this workflow builds an image named `mattermostdevelopment/mm-te-test`, it's not `mattermost/mattermost-team-edition` and I can't find where this image is built.

**Comment by amyblais** [comment]
Thank you for your interest in helping with this issue. I've shared this report internally to our team to see if one of our team members is able to help with more information. The [DevOps channel](https://community.mattermost.com/core/channels/build) on our community server is also one good place to follow-up on this issue.

**Comment by hibobmaster** [comment]
Here is my working steps for arm64 device.
```
cd ~/build/mattermost
wget https://raw.githubusercontent.com/mattermost/mattermost/master/server/build/entrypoint.sh
```
Create a Dockerfile and edit version `9.2.1` to match your need.
```
FROM ubuntu:jammy

# Setting bash as our shell, and enabling pipefail option
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Some ENV variables
ENV PATH="/mattermost/bin:${PATH}"
ARG PUID=2000
ARG PGID=2000
ARG MM_PACKAGE="https://releases.mattermost.com/9.2.1/mattermost-9.2.1-linux-arm64.tar.gz?src=docker"

# # Install needed packages and indirect dependencies
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
  ca-certificates \
  curl \
  mime-support \
  unrtf \
  wv \
  poppler-utils \
  tidy \
  tzdata \
  && rm -rf /var/lib/apt/lists/*

# Set mattermost group/user and download Mattermost
RUN mkdir -p /mattermost/data /mattermost/plugins /mattermost/client/plugins \
  && addgroup -gid ${PGID} mattermost \
  && adduser -q --disabled-password --uid ${PUID} --gid ${PGID} --gecos "" --home /mattermost mattermost \
  && if [ -n "$MM_PACKAGE" ]; then curl $MM_PACKAGE | tar -xvz ; \
  else echo "please set the MM_PACKAGE" ; exit 127 ; fi \
  && chown -R mattermost:mattermost /mattermost /mattermost/data /mattermost/plugins /mattermost/client/plugins

# We should refrain from running as privileged user
USER mattermost

#Healthcheck to make sure container is ready
HEALTHCHECK --interval=30s --timeout=10s \
  CMD curl -f http://localhost:8065/api/v4/system/ping || exit 1

# Configure entrypoint and command
COPY --chown=mattermost:mattermost --chmod=765 entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
WORKDIR /mattermost
CMD ["mattermost"]

EXPOSE 8065 8067 8074 8075

# Declare volumes for mount point directories
VOLUME ["/mattermost/data", "/mattermost/logs", "/mattermost/config", "/mattermost/plugins", "/mattermost/client/plugins"]
```
Build arm64 docker image
```
docker build . -t mattermost-arm:9.2.1
```

---

Mattermost working directory setup
```
cd /opt/mattermost
mkdir -p mattermost/{config,data,logs,plugins,bleve-indexes}
mkdir -p mattermost/client/plugins
chown 2000:2000 -R .
```
Create a `compose.yaml` file, edit `chat.example.com` to your domain name
```yaml
services:
  postgres:
    container_name: postgres_mattermost
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mattermost
      - POSTGRES_PASSWORD=mattermost
      - POSTGRES_DB=mattermost

  mattermost:
    depends_on:
      - postgres
    container_name: mattermost
    image: mattermost-arm:9.2.1
    restart: unless-stopped
    ports:
      - 127.0.0.1:8065:8065
    volumes:
      - ./mattermost/config:/mattermost/config
      - ./mattermost/data:/mattermost/data
      - ./mattermost/logs:/mattermost/logs
      - ./mattermost/plugins:/mattermost/plugins
      - ./mattermost/client/plugins:/mattermost/client/plugins
      - ./mattermost/bleve-indexes:/mattermost/bleve-indexes
    environment:
      # necessary Mattermost options/variables (see env.example)
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mattermost:mattermost@postgres:5432/mattermost?sslmode=disable&connect_timeout=10

      # necessary for bleve
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes

      # additional settings
      - MM_SERVICESETTINGS_SITEURL=https://chat.example.com
```
Spin up container
```
docker compose up
```
If it looks okay, `Ctrl+C` then run the container in detach mode.
```
docker compose up -d
```

Cheers!
