### ISSUE TITLE
Unable to access Boards in Mattermost Desktop

### ISSUE THREAD

**Issue by craph** [mattermost/mattermost-server#23536]
#### Summary
I'm unable to access Boards in Mattermost Desktop 

#### Steps to reproduce
After deploying Mattermost-server in docker with the version 7.10.2 I'm unable to access Boards in Mattermost desktop

#### Expected behavior
Boards should be accessible

#### Observed behavior (that appears unintentional) 
At the top of Mattermost desktop, when I clicked on the tab Boards nothing happen.

**Comment by amyblais** [comment]
Hi @craph,

1. What Mattermost desktop app version are you using?
2. What OS and version are you using?
3. Does this only happen on desktop app, or does this also happen on webapp?

**Comment by amyblais** [comment]
Thank you, I also combined the two reports into one since these likely have the same root cause.

**Comment by craph** [comment]
After checking the "plugins" directory I saw that all the folders were empty. After removing all the folders and restarting the docker container all the plugins were installed correctly.

May be there are an issue if folder already exists ?

**Comment by amyblais** [comment]
> After checking the "plugins" directory I saw that all the folders were empty. After removing all the folders and restarting the docker container all the plugins were installed correctly. May be there are an issue if folder already exists ?

@mickmister @hanzei Have you seen a similar issue in the past? Do you know if this could be a bug?

**Comment by hanzei** [comment]
@amyblais I've not seen that issue in the past. Maybe it's best to create a JIRA for further investigation?

**Comment by mickmister** [comment]
@amyblais @hanzei I think this may be related to https://github.com/mattermost/mattermost-plugin-playbooks/issues/1848

**Comment by mgdelacroix** [comment]
I've been trying with no success. Could you post your `docker-compose.yml` file (anonymized if necessary) so I can try and reproduce using an environment as similar as possible?

**Comment by mgdelacroix** [comment]
Could you please check what are the permissions set on the volume that stores the plugin data and in one of the plugin directories? (for example, `/mattermost/plugins` and `/mattermost/plugins/focalboard`). Are you setting custom `UID` and `GID` values for the container?

**Comment by craph** [comment]
Hello @mgdelacroix,

Sorry to answer you so late. 
Here are the permissions set on plugins data and plugins directories : 
```bash
[root@myserver mattermost]# ll -n
total 20
drwxr-xr-x  3 2000 1680 4096 Nov  8  2021 client
drwxr-xr-x  2 2000 1680 4096 May 30 10:56 config
drwxr-xr-x 16 2000 1680 4096 Jul  6 07:26 data
drwxr-xr-x  2 2000 1680 4096 Nov 13  2019 logs
drwxr-xr-x  6 2000 1680 4096 Jul  6 07:26 plugins
[root@myserver mattermost]# ll -n plugins/
total 16
drwxr--r-- 4 2000 2000 4096 Jul  6 07:26 com.mattermost.apps
drwxr--r-- 6 2000 2000 4096 Jul  6 07:26 com.mattermost.calls
drwxr--r-- 7 2000 2000 4096 Jul  6 07:26 focalboard
drwxr--r-- 6 2000 2000 4096 Jul  6 07:26 playbooks
[root@myserver mattermost]# ll -n plugins/focalboard
total 24
drwxr--r-- 2 2000 2000 4096 Jul  6 07:26 assets
drwxr--r-- 3 2000 2000 4096 Jul  6 07:26 pack
-rw-r--r-- 1 2000 2000 1270 Jul  6 07:26 plugin.json
drwxr--r-- 2 2000 2000 4096 Jul  6 07:26 public
drwxr--r-- 3 2000 2000 4096 Jul  6 07:26 server
drwxr--r-- 3 2000 2000 4096 Jul  6 07:26 webapp
```

I haven't define specific UID and GID. I have the default .env file (I'm only changing the tag for mattermost version in it)

Here is the `docker-compose.yml` file : 
```yaml
# https://docs.docker.com/compose/environment-variables/

version: "2.4"

services:
  postgres:
    container_name: postgres_mattermost
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /run/postgresql
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    environment:
      # timezone inside container
      - TZ

      # necessary Postgres options/variables
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  mattermost:
    depends_on:
      - postgres
    container_name: mattermost
    image: mattermost/${MATTERMOST_IMAGE}:${MATTERMOST_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: ${MATTERMOST_CONTAINER_READONLY}
    tmpfs:
      - /tmp
    volumes:
      - ${MATTERMOST_CONFIG_PATH}:/mattermost/config:rw
      - ${MATTERMOST_DATA_PATH}:/mattermost/data:rw
      - ${MATTERMOST_LOGS_PATH}:/mattermost/logs:rw
      - ${MATTERMOST_PLUGINS_PATH}:/mattermost/plugins:rw
      - ${MATTERMOST_CLIENT_PLUGINS_PATH}:/mattermost/client/plugins:rw
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # # to avoid Token request failed: certificate signed by unknown authority
      # # (link: https://github.com/mattermost/mattermost-server/issues/13059 and https://github.com/mattermost/docker/issues/34)
      - ${GITLAB_PKI_CHAIN_PATH}:/etc/ssl/certs/my_pki_chain.pem:ro
    environment:
      # timezone inside container
      - TZ

      # necessary Mattermost options/variables (see env.example)
      - MM_SQLSETTINGS_DRIVERNAME
      - MM_SQLSETTINGS_DATASOURCE

      # additional settings
      - MM_SERVICESETTINGS_SITEURL
```
