### ISSUE TITLE
Unable to start WebRTC Video call

### ISSUE THREAD

**Issue by Aschen** [mattermost/mattermost-server#7469]
#### Summary
I'm unable to start video call in Mattermost. 

#### Steps to reproduce
I'm using **Mattermost 4.2.0** (build hash: a5ce36d0882ae1b4b409a7b68233bf89591a5f95 ) with docker-compose. I use Nginx (reverse proxy mode) to redirect request on my Mattermost url to the container port.  
I'm redirecting HTTP request to HTTPS in Nginx to ensure SSL.  
I'm using [mattermost-webrtc](https://github.com/mattermost/mattermost-webrtc) with default configuration on the same server (I have just run the docker container).
I'm using **Google Chrome 61**.
Here you can see WebRTC configuration in the system console : 
<img width="868" alt="screen shot 2017-09-18 at 23 15 01" src="https://user-images.githubusercontent.com/4447392/30565087-57ffa7cc-9cc7-11e7-9c2f-ac21f467be42.png">
**Enable Insecure Outgoing Connections** is on.

If someone want to try it directly on my server, I can give you an access.

#### Expected behavior
Making a video call with someone of my team.  
I have tested on https://pre-release.mattermost.com and it works perfectly.

#### Observed behavior (that appears unintentional) 
When I try to call someone with the web application, I get the following message on both sides : 
`There was a problem connecting the video call.`  
In the developer console I can see that the request to `/api/v4/webrtc/token` end up with an error 500.  
<img width="1111" alt="screen shot 2017-09-18 at 22 37 42" src="https://user-images.githubusercontent.com/4447392/30564857-a09a6d10-9cc6-11e7-9e80-99a77abe7d72.png">

Here is the json returned by the request: 
```
{ 
 detailed_error : "",
 id : "model.client.connecting.app_error",
 message : "We encountered an error while connecting to the server",
 request_id : "y1maqe3cnpbct8jnpbi75ij97o",
 status_code : 500
}
```

**Comment by lindy65** [comment]
Hi @Aschen 

Thank you for your feedback,

Could you tell me whether you have `Enable the ability to make and receive one-on-one WebRTC calls` ticked in Main Menu > Account Settings > Advanced > Preview pre-release features?

**Comment by Aschen** [comment]
Hi @lindy65,
Thank you for your quick answer ;)

Yes I have enabled the pre-release feature in both account.

**Comment by lindy65** [comment]
Pleasure @Aschen 

I'll post your issue to our team and see if someone can help :)

**Comment by enahum** [comment]
By the look of the response that you are getting it looks like your mattermost instance cannot reach dockerhost

**Comment by Aschen** [comment]
@enahum 
I have change the configuration, I removed `dockerhost` and I replace it with the corresponding ip.  
<img width="814" alt="screen shot 2017-09-19 at 11 12 36" src="https://user-images.githubusercontent.com/4447392/30584924-8cbb9d68-9d2b-11e7-8599-bcfad323089e.png">

On the `mattermost_app` container : `docker exec -it mattermost_app_1 bash` 
```
root@111008d4e576:/mattermost/bin# nc 172.18.0.1 8189
Hello mattermost-webrtc
HTTP/1.0 403 Forbidden
server: libwebsockets
content-type: text/html
content-length: 38

<html><body><h1>403</h1></body></html>
```

I ended with exactly the same error.

**Comment by enahum** [comment]
@Aschen are you using docker-compose? is the webrtc container inside your docker-compose or are you using a separate image for that?

If you are running a separate image for the webrtc container you'll need to do some adjustments to your docker-compose.yaml file cause it may be that the containers are not in the same network nor they can reach each other.

for each service is your docker-compose.yaml file include `network_mode: bridge` then for the app service also include
```
external_links:
 - name-of-your-webrtc-container
```

save the file, run `docker-compose stop`, ensure your `name-of-your-webrtc-container` is running and then run `docker-compose up` or `docker-compose start`

I just tested this as you can see in the attachments
![image](https://user-images.githubusercontent.com/6757047/30588445-25d50db4-9d0d-11e7-8a8a-a7b308e68405.png)
![image](https://user-images.githubusercontent.com/6757047/30588460-314c71e6-9d0d-11e7-8d6b-194252077f3d.png)

**Comment by Aschen** [comment]
Yes I'm using docker-compose for Mattermost and my WebRTC container is in a separate container.  
I tried to add `network_mode`and `external_links` but it result with a failure (the app container can't reach the database container).  
Here is my `docker-compose.yml` with your advises : 
```
version: "2"

services:

  db:
    build: db
    restart: unless-stopped
    volumes:
      - /home/******/www/mattermost/database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mattermost_user
      - POSTGRES_PASSWORD=********
      - POSTGRES_DB=mattermost
    network_mode: bridge

  app:
    build:
      context: app
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - /home/******/www/mattermost/app/config:/mattermost/config:rw
      - /home/******/www/mattermost/app/data:/mattermost/data:rw
      - /home/******/www/mattermost/app/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mattermost_user
      - MM_PASSWORD=*********
      - MM_DBNAME=mattermost
    depends_on:
      - db
    network_mode: bridge
    external_links:
      - mattermost-webrtc
```

Are you sure that the problem is caused by a network failure ?  
Because when I am inside the `mattermost_app_1` container, I can ping the `mattermost-webrtc` container. I can also open a connection with netcat to the port `8189` used by wss protocol.

**Comment by Aschen** [comment]
Re,

I edited `docker-compose.yml` to include the webrtc container : 
```
version: "2"

services:

  db:
    build: db
    restart: unless-stopped
    volumes:
      - /home/******/www/mattermost/database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mattermost_user
      - POSTGRES_PASSWORD=********
      - POSTGRES_DB=mattermost
    network_mode: bridge

  app:
    build:
      context: app
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - /home/******/www/mattermost/app/config:/mattermost/config:rw
      - /home/******/www/mattermost/app/data:/mattermost/data:rw
      - /home/******/www/mattermost/app/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mattermost_user
      - MM_PASSWORD=*********
      - MM_DBNAME=mattermost
    depends_on:
      - db
    network_mode: bridge
    external_links:
      - mattermost-webrtc
```

**Comment by Aschen** [comment]
Re,

I edited `docker-compose.yml` to include the webrtc container : 
```
version: "2"

services:

  webrtc:
    image: mattermost/webrtc
    restart: unless-stopped
    ports:
      - "7088:7088"
      - "7089:7089"
      - "8188:8188"
      - "8189:8189"

  db:
    build: db
    restart: unless-stopped
    volumes:
      - /home/******/www/mattermost/database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mattermost_user
      - POSTGRES_PASSWORD=********
      - POSTGRES_DB=mattermost
    network_mode: bridge

  app:
    build:
      context: app
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - /home/******/www/mattermost/app/config:/mattermost/config:rw
      - /home/******/www/mattermost/app/data:/mattermost/data:rw
      - /home/******/www/mattermost/app/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mattermost_user
      - MM_PASSWORD=*********
      - MM_DBNAME=mattermost
    depends_on:
      - db
    network_mode: bridge
    external_links:
      - mattermost-webrtc
```
I edited the mattermost configuration accordingly and now it works ! 

<img width="839" alt="screen shot 2017-09-19 at 14 37 47" src="https://user-images.githubusercontent.com/4447392/30592724-39ed5758-9d48-11e7-9d72-532e4286551e.png">

I mean I don't have an error 500 anymore but I still have the message `There was a problem connecting the video call.`

I also test with my server public IP in mattermost WebRTC config (`Gateway Admin URL` and Gateway Admin Secret`) and I don't see 500 anymore too but it doesn't work neither.  
Here is the response : 
```
{"token":"Y3o5enJ5N21lYmZyaThrcXRvZ29xZTM5YW8=","gateway_url":"wss://188.***.***.***:8189"}
```
